[package]
name = "windot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
pretty_env_logger = "0.5.0"
winit = "0.28.6"
