[package]
name = "windot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cli-clipboard = "0.4.0"
dirs = "5.0.1"
gtk = { version = "0.9.0", package = "gtk4", features = ["v4_14"] }
serde = { version = "1.0.204", features = ["derive"] }
emojis = { git = "https://github.com/rossmacarthur/emojis", branch = "serde", features = ["serde"] }
toml = "0.8.15"
serde_json = "1.0.120"
