[package]
name = "windot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cli-clipboard = "0.4.0"
emojis = "0.6.0"
enigo = { version = "0.2.1", features = ["wayland"] }
gtk = { version = "0.9.0", package = "gtk4", features = ["v4_14"] }
